### ISSUE TITLE
Needs a place to mount Tutorials

### ISSUE THREAD

**Issue by bsbodden** [redis-developer/redis-developer.github.io#10]
I'm working on a **Spring Data Redis** series of screencasts and an accompanying set of articles, one large, a tutorial, and then a few on refactoring certain aspects of the app. Ideally, we should have, per programming language and even per -framework, if there is enough content (like Spring.io):

- **Getting Started Guides**: 15-30 minute read
- **Topical Guide**s: 60 minutes or less
- **Tutorials**: 2-3 hours

**Comment by tgrall** [comment]
My suggestion:

* we create a folder `/docs/tutorials` in which we drop the content that we can reference in many pages.

* in the same time we can see if a plugin exist (or create one) that use the tags to dynamically create content.

**Comment by bsbodden** [comment]
Ok, I'll hang my article under `/docs/tutorials` and I'll link it from `/develop/java#develop-with-spring`

**Comment by dashaun** [comment]
/develop
/howtos
/tutorials

Are all populated now.  Closing.
