### ISSUE TITLE
Fix "Create Database" look and feel

### ISSUE THREAD

**Issue by ajeetraina** [redis-developer/redis-developer.github.io#24]
Can we improve https://developer.redislabs.com/create/ page in terms of

1. The boxes are too small
2. The logo are not properly aligned in the center
3. The click on the box should take developers to the next page(rather than clicking on the text)

Cc: @educarneiro

**Comment by tgrall** [comment]
@ajeetraina It is done can you check and close/comment based on your test

**Comment by ajeetraina** [comment]
LGTM
