### ISSUE TITLE
Update Create RE Cloud Content

### ISSUE THREAD

**Issue by educarneiro** [redis-developer/redis-developer.github.io#30]
https://developer.redislabs.com/create/cloud

In the first paragraph, could we please update the link and format as the following?

From:
You will have to create Redis Cloud account by visiting link below.

To:
Create your free [Redis Enterprise Cloud account](https://redislabs.com/try-free/).

Tip: always look to have strong anchor text when linking. (click here, see below, etc., should be avoided)

**Comment by tgrall** [comment]
I have updated the document accordingly please check and close the issue if you are ok with it

**Comment by educarneiro** [comment]
Updated the link.
