### ISSUE TITLE
Disable Dark Mode Toggle

### ISSUE THREAD

**Issue by educarneiro** [redis-developer/redis-developer.github.io#31]
Please disable the toggle. The team is working on the CSS but it won't be ready for this launch.

**Comment by tgrall** [comment]
Enabling/Disabling this is done using the 

```
    colorMode: {
      // Hides the switch in the navbar
      // Useful if you want to support a single color mode
      disableSwitch: true,
    },
```

in the config file.

See 
https://v2.docusaurus.io/docs/2.0.0-alpha.69/theme-classic/#color-mode---dark-mode
