### ISSUE TITLE
Add link to redisforum

### ISSUE THREAD

**Issue by ajeetraina** [redis-developer/redis-developer.github.io#51]
A reference link to https://forum.redislabs.com/ is missing in our developer site.  It would be great to add it.

**Comment by tgrall** [comment]
I did add one in this page:

https://developer.redislabs.com/guides/indexing/

We should do in multiple places and probably the footer

**Comment by ajeetraina** [comment]
@educarneiro Command Reference link is displaying twice - on the top nav as well as footer.  May be it would be good idea to replace it with RedisForum.
